import { Product } from './types';

export const PRODUCTS: Product[] = [
  {
    id: 'blazer-01',
    name: 'Premium Institutional Blazer',
    description: 'A meticulously tailored school blazer with double stitching and institutional gold crest compatibility. Sourced for exceptional durability and soft luxury hand-feel.',
    price: 65.00,
    bulkPrice: 55.00,
    category: 'school',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAL6TaUprv40aW1-mM6vAYjzId_muH5whOYWPIem4lHZlTegAX1VIha8TCia-nQ3U50HUVHHqvM9PeASclgyrdbPAFgvZqTaJKfLWTEnI9J6y3-0v-faWPec2OCd4W0-XnH90z2tohOdQwTgDy5tgAgR5ZjgH2lz7VhoQwMYDi_jR3Pxm6U2a6YWMXaHiIUhFr5gUR6W7MZzZZuLyBpo-FmGcE_nU4Gz7E4hHJP1I0mFwWYOyh1OW1GqP_JHkUTa32xAByPcsfJ6aA',
    isBestSeller: true,
    subcategory: 'Premium Blazers',
    fabric: 'Premium Wool Blend',
    gender: 'unisex',
    ageGroup: 'senior',
    schoolLogo: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCOguUi6B9bznWurw-EDLHimdyXYqRct0UBo8vU1mI2SGYGA8a7fre3ffL9DFZ6pqAqvlRxwXBp-OR6DHrVquaLOehF4fTvgtOScemmkTryE4xCoOXPUVrXogLuOjpHQz-ih5qW3jFT5xigOA4jc18DevGieT3aPtA3JkNfRrEaxqY5eZWMcAQmSkyYYj5ece9-2U6ZxrmKSztW3QD0dK1n6NMscUBFUJLRRMVhgs3Dk9KUXxrkWxb8r1LU6fJXz3j8d8UeRLhcNBU',
    colors: ['#003f7c', '#2e3036', '#6b2c00'],
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL']
  },
  {
    id: 'shirt-01',
    name: 'Boys Premium White Shirt (Full Sleeve)',
    description: 'Crisp, high-quality, long-sleeve school uniform shirt. Easy-iron fabric makes it a household favorite while ensuring students look exceptionally smart all day.',
    price: 24.00,
    bulkPrice: 20.00,
    category: 'school',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDvmrL9S6UJcOvxn_QTnk4zjcMo-jDDWaUCXCIWgOA8wwRVtqZLFxBL5sOcXHCMTd3WzrQavNiYH2NG-_aDiPWRBLDhQsdlvVuSxaHASQCENcuWGqEB-8IWk88YSiMVelJGrF7p_WnM834YdS0jLjpE5pt5y2c8APl6qBeZsb5Mg0S-xL-9ZMHdl8FLWUqAiSJPRlBO1IQ3xzLsAbiafw2DY8xyL4SdnkzxUUKZth6bCxiHEnMQ-Oimo0AEvt3i-v19PKBIrLoEs3U',
    subcategory: 'Daily Uniform',
    fabric: '100% Cotton',
    gender: 'boys',
    ageGroup: 'junior',
    schoolLogo: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCOguUi6B9bznWurw-EDLHimdyXYqRct0UBo8vU1mI2SGYGA8a7fre3ffL9DFZ6pqAqvlRxwXBp-OR6DHrVquaLOehF4fTvgtOScemmkTryE4xCoOXPUVrXogLuOjpHQz-ih5qW3jFT5xigOA4jc18DevGieT3aPtA3JkNfRrEaxqY5eZWMcAQmSkyYYj5ece9-2U6ZxrmKSztW3QD0dK1n6NMscUBFUJLRRMVhgs3Dk9KUXxrkWxb8r1LU6fJXz3j8d8UeRLhcNBU',
    colors: ['#ffffff'],
    sizes: ['S', 'M', 'L', 'XL']
  },
  {
    id: 'trousers-01',
    name: 'Boys Navy Blue Trousers (Regular Fit)',
    description: 'Premium tailored navy blue trousers with reinforced knees and adjustable waistband. Fabric is treated for stain-resistance and holds up beautifully under intensive play.',
    price: 32.00,
    bulkPrice: 28.00,
    category: 'school',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuC1leemNqHvkTEY46oINaZsXLw1h-Hcjn1goF2nXm0yQo0Z5AoZ79nShYUMtXf1naQ8ue7y--Lx9CcBRaC3LNNgUrjA5hGmjc324GmRXsULBPBPMXfX9RU2-ENQ4tHInGMSXUUqGRIzh8GYe64FDdXOq8QeSPrtnFzDVTAsR33sKz6jzBZXfwlMyRKAc4KWEtZM0_QvMxjhtDq7Izuxy3rVUcgn4cjUkRrGErNzp7oUyo-XB3DtgkkVXsJ6nAkaFGkw7R5yyLR2_Rk',
    subcategory: 'Daily Uniform',
    fabric: 'Poly Cotton',
    gender: 'boys',
    ageGroup: 'junior',
    schoolLogo: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCOguUi6B9bznWurw-EDLHimdyXYqRct0UBo8vU1mI2SGYGA8a7fre3ffL9DFZ6pqAqvlRxwXBp-OR6DHrVquaLOehF4fTvgtOScemmkTryE4xCoOXPUVrXogLuOjpHQz-ih5qW3jFT5xigOA4jc18DevGieT3aPtA3JkNfRrEaxqY5eZWMcAQmSkyYYj5ece9-2U6ZxrmKSztW3QD0dK1n6NMscUBFUJLRRMVhgs3Dk9KUXxrkWxb8r1LU6fJXz3j8d8UeRLhcNBU',
    colors: ['#003f7c', '#2e3036'],
    sizes: ['24', '26', '28', '30', '32', '34']
  },
  {
    id: 'polo-01',
    name: 'Classic White Polo T-Shirt',
    description: 'Crisp, double-knit pique polo t-shirt with ribbed collar and cuffs. High breathability ensures comfort during study and light sports activities.',
    price: 18.00,
    bulkPrice: 14.00,
    category: 'school',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuB6Mqh1gDa7oOM5_toMZocISkUhfUssQ9YGPeh5ZmIfNbsqFtTfD5V7MaVxAYcMU46wUEEKR8XmBm7bo6Q-pM058-XYexxBN5yBy2iONToCGgUyYtnjCIvYKFnn_a8G3Kyr-fX8-n1PX4jHDGlisOTgjbY1UTgrhNbXCqWhEYQ00MORbGvxlo-RvlIFu9QbD2zsvnsBFFXLrEEtzMr0APV_jdQDuSJjv_Zk-w9ukzzEY885hkjTZNfhxF63NCZCHmgqMcvF_ltB66g',
    subcategory: 'Polo T-Shirts',
    fabric: 'Cotton Pique',
    gender: 'unisex',
    ageGroup: 'junior',
    schoolLogo: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCOguUi6B9bznWurw-EDLHimdyXYqRct0UBo8vU1mI2SGYGA8a7fre3ffL9DFZ6pqAqvlRxwXBp-OR6DHrVquaLOehF4fTvgtOScemmkTryE4xCoOXPUVrXogLuOjpHQz-ih5qW3jFT5xigOA4jc18DevGieT3aPtA3JkNfRrEaxqY5eZWMcAQmSkyYYj5ece9-2U6ZxrmKSztW3QD0dK1n6NMscUBFUJLRRMVhgs3Dk9KUXxrkWxb8r1LU6fJXz3j8d8UeRLhcNBU',
    colors: ['#ffffff', '#f2f3fb', '#003f7c'],
    sizes: ['XS', 'S', 'M', 'L']
  },
  {
    id: 'daily-01',
    name: 'Girls Daily Uniform Combo Set',
    description: 'An elegant matching set of a daily pressed sky-blue uniform shirt and premium grey pleated skirt. Durable fibers remain flat and neat without heavy ironing.',
    price: 45.00,
    bulkPrice: 38.00,
    category: 'school',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDIVWhJCrGeEgdKRzKZm6Az_KSfrVCXXIY1Hxda9kU6nQyviZ788yY70JXqKYCzdusC_NXvHy1MQPur-Ls0suAgsDSP6RFe9n8V031x-kXLkJRv5Rs6Lg2qcEbUWc7363xkiMneXlxY0h1N38adr3hFlpba5pINKsGshD2CeqN5KF-vDqdF2JenW8F35qpgBxhip_5-Szv5JP922fWK8kTOa4PBLi3GsL4GQzLxGjr_46N4CYgVUW2ZY_Hu31nkWtCr2D_1_ZL1Zk0',
    subcategory: 'Daily Uniform',
    fabric: 'Poly Cotton',
    gender: 'girls',
    ageGroup: 'junior',
    schoolLogo: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCOguUi6B9bznWurw-EDLHimdyXYqRct0UBo8vU1mI2SGYGA8a7fre3ffL9DFZ6pqAqvlRxwXBp-OR6DHrVquaLOehF4fTvgtOScemmkTryE4xCoOXPUVrXogLuOjpHQz-ih5qW3jFT5xigOA4jc18DevGieT3aPtA3JkNfRrEaxqY5eZWMcAQmSkyYYj5ece9-2U6ZxrmKSztW3QD0dK1n6NMscUBFUJLRRMVhgs3Dk9KUXxrkWxb8r1LU6fJXz3j8d8UeRLhcNBU',
    colors: ['#64748b', '#003f7c'],
    sizes: ['XS', 'S', 'M', 'L']
  },
  {
    id: 'winter-01',
    name: 'Premium Knitted V-Neck Sweater',
    description: 'Warm, cozy school sweater made with an anti-pilling premium wool blend. Soft lining keeps students warm in breezy mornings while maintaining high breathability.',
    price: 38.00,
    bulkPrice: 30.00,
    category: 'school',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuC-GeEpDaa7kAKe8VmYVXeNS7eB3I8_M18ASDLe-KsWeV8SkDC3UgyPSnA2wMuwecZC5-JDGhONprhuzIr-qzGK5UZKBSorfMIzsEhPQ7a5WKrSsz-Kx6SulkCRCGLC89Wq-mcAxiI8CHCTHkD8IRFrlz0cIM5mG7rzOsbIiECOiT3jzMzE5kemcg-dYrGrTVf-fvjEuTT8UOXF7klP0ZEnxfqPyxo7wd0itEiW1c-QY3MP6aUMt-rNFbFU7LGPH4uDsGjAopq-cDU',
    subcategory: 'Winter Wear',
    fabric: 'Anti-Pilling Wool Blend',
    gender: 'unisex',
    ageGroup: 'senior',
    schoolLogo: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCOguUi6B9bznWurw-EDLHimdyXYqRct0UBo8vU1mI2SGYGA8a7fre3ffL9DFZ6pqAqvlRxwXBp-OR6DHrVquaLOehF4fTvgtOScemmkTryE4xCoOXPUVrXogLuOjpHQz-ih5qW3jFT5xigOA4jc18DevGieT3aPtA3JkNfRrEaxqY5eZWMcAQmSkyYYj5ece9-2U6ZxrmKSztW3QD0dK1n6NMscUBFUJLRRMVhgs3Dk9KUXxrkWxb8r1LU6fJXz3j8d8UeRLhcNBU',
    colors: ['#003f7c', '#2e3036', '#ba1a1a'],
    sizes: ['S', 'M', 'L', 'XL']
  },

  // Sports Category
  {
    id: 'sport-kit-01',
    name: 'Pro-Elite Football Kit (Combo Set)',
    description: 'High-performance team soccer jersey and matching elastic shorts. Configured with dynamic micro-ventilation zones to wick moisture away during 90 minutes of peak field play.',
    price: 48.00,
    bulkPrice: 38.00,
    category: 'sports',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCSwiRCNU9nXD6XGke9xZDXAaL1ab1pLbJPfTIpdMF4-10Trm1T41poQ2z9JQIbNOY1NtRroUN2a4wT1u5eHVX5Jr0IB6cdV6ZBh73odp9LuZdeRqEWsf2-3p3Ul1s8gW4dBbhT-VLHMgOKp4dp_kKzeM_CUxmiOTmK43_JljZSs3Qf2OGM6w6wcc0_CbcnSGfZ07W-bbolbvc-wbON6G3zV5wel1KqGcZ9lWC8ZV-NzIRbf6mZNuJHL9nowFXWQ-4hTXXRSq1tFVo',
    isBestSeller: true,
    subcategory: 'Pro-Elite Football Kits',
    fabric: 'Micro-Ventilation Dry-Fit',
    gender: 'unisex',
    ageGroup: 'senior',
    colors: ['#003f7c', '#ba1a1a', '#f2c027'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL']
  },
  {
    id: 'sport-shirt-01',
    name: 'Aero-Breathe Training Tee',
    description: 'Flat-laid active sports training t-shirt. Integrated side panels provide extreme ventilation while high tensile strength poly fibers resist tearing.',
    price: 34.00,
    bulkPrice: 28.00,
    category: 'sports',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuD2kmJ6VdGbePqZRyBxi1G0s7kEG-O_HYwi0mhpQpZnawqfg7BZN0ojue23nIhJNLVJxgT9T06CXkQ15slhzvsYhNZ0tQqDKCOjvluwC4gnw2IxOx55Z08RreO4CoeAMAhtr__T4wQQvx5bXJjdDk6tsnnMG-N9y40vlSnwTaQydQIuEBRuxYBNEq9JTM9XSaQnpocCFhzakSYsPXjip1sbroFZlSmkCdw5LvO4KdLavI8Yk9rH8l_T0AxBgdDwLhyqoWcusuisQTA',
    subcategory: 'T-Shirts',
    fabric: 'Dry-Fit Mesh',
    gender: 'unisex',
    ageGroup: 'senior',
    colors: ['#003f7c', '#2e3036'],
    sizes: ['S', 'M', 'L', 'XL']
  },
  {
    id: 'sport-track-01',
    name: 'Thermal Flex Track Set',
    description: 'Sleek, tailored modern athletic tracksuit set consisting of premium fleece zip-up jacket and tapered pants. Brushed interior lock-in warmth.',
    price: 85.00,
    bulkPrice: 75.00,
    category: 'sports',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAB2F5fWVuQbG640TCq3ob1kYkG5IBYZaHXiOpoEV65dN53YXJjXE6MSApNOUJUsWbOFrhOQ7M8eJruFgjZBlKnILCWd-fIgp6dLnO8T8Uusen50FPXl_JL8npvjv6ukuZ79DvEkKBW3TgkpFPcQWTX9f0w9S31EHQxMTqECzsNn6QKS0AQESZbvYvitSZfth13MpQlsoExcsULa6EuinN4I1TkliitCkYEspKS2BHbsBgJ95K3Klx_Ws71_0ORa3xr0wksRd1115A',
    subcategory: 'Tracksuits',
    fabric: 'Tech Poly Fleece',
    gender: 'unisex',
    ageGroup: 'senior',
    colors: ['#2e3036', '#003f7c'],
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL']
  },
  {
    id: 'sport-shorts-01',
    name: 'Agility Court Sports Shorts',
    description: 'Designed for high impact indoor/outdoor courts. Lightweight material ensures ultimate jumping and sprinting agility with split seams for flexible strides.',
    price: 28.00,
    bulkPrice: 22.00,
    category: 'sports',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCVzUUACvuT45-z8EMPFhHeBx7TEZoutVniQOidCzW-uJKkgyPh75ssrHQDYmTAJWFGtoobHZWvztannHBG9rn8U2kXnjux8xFVWrsKKlW3p3dlkiAoYBHqaIXwIt0eMmZKaiCGtiX0m0nCqZtxZyoJq5OFAuA4lPMUQNv64cRu-v770Q3Lh2cFdItL8KdgZehlLK20nKZIQ_io4gEK1MmXBdxHUYhMaL6vpx_XfVV7iioC00T4FXfmoTv7mgTZ8xsv1OaXMlCfiec',
    subcategory: 'Bottoms',
    fabric: 'Dry-Fit Stretch',
    gender: 'unisex',
    ageGroup: 'junior',
    colors: ['#003f7c', '#64748b'],
    sizes: ['S', 'M', 'L', 'XL']
  },
  {
    id: 'sport-cricket-01',
    name: 'Academic Cricket Kit',
    description: 'Pristine white academic cricket set. Features mesh panels under arms, standard polo collar with subtle navy blue piping, and premium durable white cricket pants.',
    price: 55.00,
    bulkPrice: 45.00,
    category: 'sports',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBOXYp-YcyfY55I50KC8x9wRQb-wHSJ5jgKeZ_WZe8dT4da5fOIzPq4aT6HjfpHgnm_QgtT8FK9D5lKpxH3RsNaxfgo87IgACVEzzJgykQs7f9le5otbNg_xplaWJH4N6OwV0OXgtpkF1QT_qD0oMnMWlm42_aMffCTZXIRmJVHrtLnBZVTeVJRzxzIkJHdeKzTjys9N_lofRmdbnecVQwurC24nX1Zz9SUKRZkkriTRmjunOE-bt9HKLL02Dq4ciz740N3So2_fdQ',
    subcategory: 'Cricket Kits',
    fabric: 'Premium Polyester',
    gender: 'boys',
    ageGroup: 'senior',
    colors: ['#ffffff'],
    sizes: ['S', 'M', 'L', 'XL']
  },
  {
    id: 'sport-house-01',
    name: 'Vibrant House Sports Dress',
    description: 'Multi-colored premium house sport garments. Double stitching and comfort fit allow student athletes to represent their team houses with pride.',
    price: 22.00,
    bulkPrice: 18.00,
    category: 'sports',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBxdFsnZxm3NQLKwc4pGOPxfriVkf51egBD7KHvtNYIu4JUSmBp_aJfZAPHyU8WFwbHy405kHKPpta_62SgEpzO0v7CWvie8lfnTI2GtU0HXrb6Ehwkim_NopMeU70Z_R-G91h4UmFYv2wLQRo0QzvppPFMX8OKAAT1Gry7yWGgaLwxItJpqG-Gem4Nq4_fdlid5VoM54FNWFdSClyvNSyL82sdCf7Msv_bYQRvK8PbeJPhVd840ASLrb6TdLFEecWst1HuyV36EQE',
    subcategory: 'House Sports Dress',
    fabric: 'Cotton-Poly Blend',
    gender: 'girls',
    ageGroup: 'junior',
    colors: ['#ba1a1a', '#003f7c', '#0056a6', '#f2c027'],
    sizes: ['XS', 'S', 'M', 'L']
  },

  // Corporate Category
  {
    id: 'corp-blazer-01',
    name: 'Executive Tailored Corporate Blazer',
    description: 'Expertly structured executive blazer in crisp wool-blend. Features double rear vents, notch lapels, and custom brass-embossed button options for elite representation.',
    price: 95.00,
    bulkPrice: 80.00,
    category: 'corporate',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAL6TaUprv40aW1-mM6vAYjzId_muH5whOYWPIem4lHZlTegAX1VIha8TCia-nQ3U50HUVHHqvM9PeASclgyrdbPAFgvZqTaJKfLWTEnI9J6y3-0v-faWPec2OCd4W0-XnH90z2tohOdQwTgDy5tgAgR5ZjgH2lz7VhoQwMYDi_jR3Pxm6U2a6YWMXaHiIUhFr5gUR6W7MZzZZuLyBpo-FmGcE_nU4Gz7E4hHJP1I0mFwWYOyh1OW1GqP_JHkUTa32xAByPcsfJ6aA',
    subcategory: 'Corporate Blazers',
    fabric: 'Premium Merino Blend',
    gender: 'unisex',
    ageGroup: 'senior',
    colors: ['#2e3036', '#003f7c'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL']
  },
  {
    id: 'corp-shirt-01',
    name: 'Executive Egyptian Cotton Shirt',
    description: 'Luxurious 100% Egyptian cotton white dress shirt. Highly resilient, breathable, and stays crisp and wrinkle-free through the longest work schedules.',
    price: 38.00,
    bulkPrice: 30.00,
    category: 'corporate',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDvmrL9S6UJcOvxn_QTnk4zjcMo-jDDWaUCXCIWgOA8wwRVtqZLFxBL5sOcXHCMTd3WzrQavNiYH2NG-_aDiPWRBLDhQsdlvVuSxaHASQCENcuWGqEB-8IWk88YSiMVelJGrF7p_WnM834YdS0jLjpE5pt5y2c8APl6qBeZsb5Mg0S-xL-9ZMHdl8FLWUqAiSJPRlBO1IQ3xzLsAbiafw2DY8xyL4SdnkzxUUKZth6bCxiHEnMQ-Oimo0AEvt3i-v19PKBIrLoEs3U',
    subcategory: 'Corporate Shirts',
    fabric: '100% Egyptian Cotton',
    gender: 'unisex',
    ageGroup: 'senior',
    colors: ['#ffffff', '#b2ceff'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL']
  },

  // Accessories Category
  {
    id: 'access-tie-01',
    name: 'Premium Crest Silk School Tie',
    description: 'Finely woven silk-blend uniform tie with double satin stripes and custom school crest placement. Strong lining maintains a perfect, tidy knot.',
    price: 12.00,
    bulkPrice: 8.00,
    category: 'accessories',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCOguUi6B9bznWurw-EDLHimdyXYqRct0UBo8vU1mI2SGYGA8a7fre3ffL9DFZ6pqAqvlRxwXBp-OR6DHrVquaLOehF4fTvgtOScemmkTryE4xCoOXPUVrXogLuOjpHQz-ih5qW3jFT5xigOA4jc18DevGieT3aPtA3JkNfRrEaxqY5eZWMcAQmSkyYYj5ece9-2U6ZxrmKSztW3QD0dK1n6NMscUBFUJLRRMVhgs3Dk9KUXxrkWxb8r1LU6fJXz3j8d8UeRLhcNBU',
    subcategory: 'Ties & Belts',
    fabric: 'Satin Silk Blend',
    gender: 'boys',
    ageGroup: 'junior',
    colors: ['#003f7c', '#ba1a1a', '#755b00'],
    sizes: ['Junior', 'Senior']
  },
  {
    id: 'access-bag-01',
    name: 'Heavy-Duty Campus Oxford Backpack',
    description: 'Completely waterproof Oxford nylon backpack with padded laptop sleeve, reinforced ergonomic straps, and dual mesh bottle pockets. Exceptional volume and durability.',
    price: 42.00,
    bulkPrice: 32.00,
    category: 'accessories',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDApSmPA60bR608w2vKg4ws41VIuZthHLIDA8_bzHqZG9hy3ShegItk_L8RuDLQzhNBbXlErzHhOo3ysJD7ujaYbVyFORm0-0mYcibUtB25IifRHlNArIDkazzfgYyJBvGZln1CYEJTr7XtsVRFOY6YrQse5jHhJ_PUkubD-chD9rCuOvv1wK0Z1EVI639h-mgTMas8YeQD8RKPYW2sVDaC2kFGVpBJcmajEADdKeU-5sbz7t30EgluSucH5HqOBIoPADa9S6HIkq4',
    subcategory: 'School Bags',
    fabric: 'Waterproof Oxford Nylon',
    gender: 'unisex',
    ageGroup: 'all',
    colors: ['#003f7c', '#2e3036'],
    sizes: ['Regular', 'Large']
  }
];

export const ALL_FABRICS = Array.from(new Set(PRODUCTS.map(p => p.fabric)));
export const ALL_SUBCATEGORIES = Array.from(new Set(PRODUCTS.map(p => p.subcategory || 'General')));
